---
apiVersion: 1
datasources:
  - uid: local-pyroscope
    type: grafana-pyroscope-datasource
    name: Pyroscope
    url: http://host.docker.internal:4040
    jsonData:
      keepCookies: [pyroscope_git_session]
