services:
  server:
    image: searxng/searxng:latest
    hostname: searxng-server
    pull_policy: always
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./config:/etc/searxng:rw
